language: node_js
sudo: false
node_js:
  - "4.3"
cache:
  directories:
  - node_modules
install:
  - npm link
  - npm install
test:
  - npm test
deploy:
  provider: npm
  api_key: $NODE_API_KEY
  on:
    tags: true
    branch: master
