language: node_js
sudo: false
node_js:
  - "4.3"
cache:
  directories:
  - node_modules
install:
  - npm link
  - npm install
script:
  - npm run lint
  - npm run test
after_script:
  - npm run coveralls
deploy:
  provider: npm
  api_key: $NPM_API_KEY
  on:
    tags: true
    branch: master
